# All about DataFrames Pandas objects
# Coded by Soumonos Mukherjee

- Read the dataset 'fandango_score_comparison' in the fandango dataframe.
- Return a dataframe containing only the first and last lines and assign the result to the first_last variable.
- Display the result.

In [1]:
import pandas as pd
import os
os.chdir("C:\\Users\\User\\Downloads\\Soumonos & Kavesh")

In [2]:
#Displaying the first and last column of the dataframe
fandango= pd.read_csv('fandango_score_comparison.csv')
first_last= fandango.iloc[[0,-1]]
first_last

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
0,Avengers: Age of Ultron (2015),74,86,66,7.1,7.8,5.0,4.5,3.70,4.30,...,3.90,3.5,4.5,3.5,3.5,4.0,1330,271107,14846,0.5
145,"Kumiko, The Treasure Hunter (2015)",87,63,68,6.4,6.7,3.5,3.5,4.35,3.15,...,3.35,4.5,3.0,3.5,3.0,3.5,19,5289,41,0.0

## Use custom indexes

- Use the set_index method to index our fandango DataFrame with the 'FILM' column. Note that we want to keep the 'FILM' column. Furthermore we want to keep the original DataFrame and create a new one that we will assign to the fandango_films variable.
- Display the index of the DataFrame fandango_films in the iade of the index attribute.

In [9]:
#Setting film name (FILM) as index
fandango_films= fandango.set_index(fandango.FILM)
fandango_films.index

Index(['Avengers: Age of Ultron (2015)', 'Cinderella (2015)', 'Ant-Man (2015)',
       'Do You Believe? (2015)', 'Hot Tub Time Machine 2 (2015)',
       'The Water Diviner (2015)', 'Irrational Man (2015)', 'Top Five (2014)',
       'Shaun the Sheep Movie (2015)', 'Love & Mercy (2015)',
       ...
       'The Woman In Black 2 Angel of Death (2015)', 'Danny Collins (2015)',
       'Spare Parts (2015)', 'Serena (2015)', 'Inside Out (2015)',
       'Mr. Holmes (2015)', ''71 (2015)', 'Two Days, One Night (2014)',
       'Gett: The Trial of Viviane Amsalem (2015)',
       'Kumiko, The Treasure Hunter (2015)'],
      dtype='object', name='FILM', length=146)

## Selecting values from an index

- Select the following movies from the DataFrame fandango_films (in the following order) and assign them to the some_movies variable:
>- "Top Five (2014)"
>- "Black Sea (2015)"
>- "Taken 3 (2015)"
- Display the result.

In [12]:
#Filtering out specific rows containing the specific filmnames and storing them as a dataframe 
some_movies= fandango_films.loc[ ['Top Five (2014)' , 'Black Sea (2015)', 'Taken 3 (2015)'] , : ]
some_movies

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
FILM,,,,,,,,,,,,,,,,,,,,,
Top Five (2014),Top Five (2014),86,64,81,6.8,6.5,4.0,3.5,4.30,3.2,...,3.25,4.5,3.0,4.0,3.5,3.5,124,16876,3223,0.5
Black Sea (2015),Black Sea (2015),82,60,62,6.6,6.4,4.0,3.5,4.10,3.0,...,3.20,4.0,3.0,3.0,3.5,3.0,37,16547,218,0.5
Taken 3 (2015),Taken 3 (2015),9,46,26,4.6,6.1,4.5,4.1,0.45,2.3,...,3.05,0.5,2.5,1.5,2.5,3.0,240,104235,6757,0.4

## Apply() method on the columns of a DataFrame

- Get the float_df dataframe I made as an example (which returns the float64 decimal columns)
- Use the apply() method on this float_df dataframe to halve each value and assign the result to the exo_df variable.
- Display the first lines of the result.

In [30]:
#Filtering out only float64 type columns 
float_df= fandango_films.select_dtypes(include="float64")
float_df.head()

,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,Metacritic_norm,Metacritic_user_nom,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Fandango_Difference
FILM,,,,,,,,,,,,,,,
Avengers: Age of Ultron (2015),7.1,7.8,5.0,4.5,3.70,4.3,3.30,3.55,3.90,3.5,4.5,3.5,3.5,4.0,0.5
Cinderella (2015),7.5,7.1,5.0,4.5,4.25,4.0,3.35,3.75,3.55,4.5,4.0,3.5,4.0,3.5,0.5
Ant-Man (2015),8.1,7.8,5.0,4.5,4.00,4.5,3.20,4.05,3.90,4.0,4.5,3.0,4.0,4.0,0.5
Do You Believe? (2015),4.7,5.4,5.0,4.5,0.90,4.2,1.10,2.35,2.70,1.0,4.0,1.0,2.5,2.5,0.5
Hot Tub Time Machine 2 (2015),3.4,5.1,3.5,3.0,0.70,1.4,1.45,1.70,2.55,0.5,1.5,1.5,1.5,2.5,0.5

In [29]:
#Applying a function to return half of each column values 
exo_df= float_df.apply(lambda x: x/2, axis=1)
exo_df.head()

,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,Metacritic_norm,Metacritic_user_nom,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Fandango_Difference
FILM,,,,,,,,,,,,,,,
Avengers: Age of Ultron (2015),3.55,3.90,2.50,2.25,1.850,2.15,1.650,1.775,1.950,1.75,2.25,1.75,1.75,2.00,0.25
Cinderella (2015),3.75,3.55,2.50,2.25,2.125,2.00,1.675,1.875,1.775,2.25,2.00,1.75,2.00,1.75,0.25
Ant-Man (2015),4.05,3.90,2.50,2.25,2.000,2.25,1.600,2.025,1.950,2.00,2.25,1.50,2.00,2.00,0.25
Do You Believe? (2015),2.35,2.70,2.50,2.25,0.450,2.10,0.550,1.175,1.350,0.50,2.00,0.50,1.25,1.25,0.25
Hot Tub Time Machine 2 (2015),1.70,2.55,1.75,1.50,0.350,0.70,0.725,0.850,1.275,0.25,0.75,0.75,0.75,1.25,0.25

In [15]:
import numpy as np

## Apply() method on the lines of a DataFrame

- Use the apply() method to calculate the average (mean() method from the Numpy library) of the values of each movie for 'RT_user_norm' and 'metacritic_user_name' and then assign the result to the variable rt_mt_means.
- Display the first 5 values of rt_mt_means.

In [33]:
#applying a function (mean) to return the average of the 2 specific columns
rt_mt_means= fandango_films[['RT_user_norm','Metacritic_user_nom']].apply(np.mean,axis=1)

In [34]:
rt_mt_means.head()

FILM
Avengers: Age of Ultron (2015)    3.925
Cinderella (2015)                 3.875
Ant-Man (2015)                    4.275
Do You Believe? (2015)            3.275
Hot Tub Time Machine 2 (2015)     1.550
dtype: float64